CREATE TABLE DOIBONG (
    MaDoi VARCHAR(20) NOT NULL PRIMARY KEY,
    TenDoi VARCHAR(100),
    QuocGia VARCHAR(40) 
);

CREATE TABLE GIAIDAU (
    MaGiai varchar(20) NOT NULL PRIMARY KEY,
    TenGiai varchar(100),
    NgayBatDau DATE,
    NgayKetThuc DATE
);



CREATE TABLE CT_GD (
 MaGiai varchar(20) NOT NULL,
 MaDoi varchar(20) NOT NULL,
 FOREIGN KEY (MaGiai) REFERENCES GIAIDAU(MaGiai),
 FOREIGN KEY (MaDoi) REFERENCES DOIBONG(MaDoi),
 PRIMARY KEY (MaGiai, MaDoi)
)


CREATE TABLE TRANDAU (
    MaTran varchar(20) NOT NULL PRIMARY KEY,
    NgayDa DATE,
    DiaDiem varchar(20),
    MaGiai varchar(20) NOT NULL,
    MaDN varchar(20) NOT NULL,
    MaDK varchar(20) NOT NULL,
    TiSo varchar(10),
    CONSTRAINT FK_TRANDAU_MaGiai FOREIGN KEY (MaGiai) REFERENCES GIAIDAU(MaGiai),
    CONSTRAINT FK_TRANDAU_MaDN FOREIGN KEY (MaDN) REFERENCES DOIBONG(MaDoi),
    CONSTRAINT FK_TRANDAU_MaDK FOREIGN KEY (MaDK) REFERENCES DOIBONG(MaDoi)
)

SELECT * FROM DOIBONG;